---
title: "Tölvuverkefni 3"
author: "Ásmundur Óskar Ásmundsson (aoa27@hi.is) og Helgi Sigtryggsson (hes86@hi.is)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pakkar, include=FALSE}
library(readr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(kableExtra)
library(tidyr)
```

## a) liður
Byrjum á því að lesa inn gögnin:
```{r, lesa gögn}
ah <- read.csv("data98.csv", sep=",")
```

```{r, búum til nýjar breytur}
r2d <-
function(r)
{
	lat <- floor(r/100)
	lon <- (r - lat * 100) %% 50
	halfb <- (r - 100 * lat - lon)/100
	lon <-  - (lon + 0.5)
	lat <- lat + 60 + halfb + 0.25
	data.frame(lat = lat, lon = lon)
}
latitude<- r2d(ah$reit)$lat
longtitude <- r2d(ah$reit)$lon
hafsvaedi <- ifelse(latitude < 65, 
                    ifelse(longtitude < -19, "SV","SA"),
                    ifelse(longtitude < -19, "NV","NA")
                    )
kt2 <- ifelse(ah$kt == 1, "Ókynþroska", "Kynþroska")
ah <- ah %>%
  mutate(hafsvaedi = factor(hafsvaedi), 
         kt2 = factor(kt2)
         )
```


## b) liður

## c) liður

## d) liður

## e) liður

## f) liður

## g) liður

## h) liður

## i) liður

## j) liður

## k) liður

## Bónusspurning
